### PR TITLE
Add google analytics tracking code

### PR DESCRIPTION
**Pull request by nberger**

### CODE REVIEW

**Comment by nberger** [comment]
@mgrunberg please review. And if it's ok, could you please deploy it too? :)

**Comment by cristianstu** [comment]
it is not enough add the code in all the layouts?

**Comment by nberger** [comment]
I think you are talking about the diffs in public... It's in the layout, but then it was propagated to all the generated posts under the public directory. I understand that we commit the generated posts in public, that explains all the differences in the public directory.

Let me know if I am missing something

**Comment by nberger** [comment]
I used `jekyll build` to regenerate the public dir

**Comment by cristianstu** [comment]
I think all the post uses this https://github.com/MavenThought/smartview-blog/blob/master/_layouts/post.html as layout but I'm not sure.

**Comment by cristianstu** [comment]
Sorry, I wasn't referring to the public files.
But no matter, we should add the code before </Head> so we can't use the layout

**Comment by mgrunberg** [comment]
:+1:
I've deployed this branch

**Comment by nberger** [comment]
Thanks. I'll merge it now.

**Pull request merged**
